spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: microsserviceGateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://cursoms-keycloak:8080/realms/mscourserealm
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://adm:adm@${EUREKA_SERVER}:8761/eureka

